# Site settings
title: "Coding Adventure: Day 1"
header-img: img/home-bg.png
email: miss.nadia.lee@gmail.com
copyright_name: missnadia
description: > # this means to ignore newlines until "baseurl:"
  My First Day at the Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  missnadia
learn_profile: missnadia
email_username: miss.nadia.lee@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
